### ISSUE TITLE
Esboço da tela de listagem de Clientes e do modal de edição de cliente

### ISSUE THREAD

**Issue by djairtb** [djairtb/FitApp#2]
- [x] Esboço de tela com lista de informações do cliente e menu lateral de navegação no app (a lista pode ser feita tanto em tabela quanto em uma lista de cards)

- [x] #4

- [x] Esboço de uma tela para consulta de informações do cliente e mudança de planos de serviço(planos mensais da academia) e também registro de pagamentos efetuados.

Um detalhe interessante é que o cadastro e edição do cliente sera separado da tela de consulta de pagamento e planos devido a divisão de responsabilidades de cada tela.

**Comment by ghost** [comment]
Esboços finalizados, aguardando para avaliações e discussões sobre.

**Comment by djairtb** [comment]
>>
